### ISSUE TITLE
Waiting for OSPd socket

### ISSUE THREAD

**Issue by 87All** [jeffleder/gvm-docker#1]
Hi, I have an issue with the gvm container. Please check the logs attached:

"Starting Redis
7:C 27 Oct 2020 11:55:26.112 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 11:55:26.112 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 11:55:26.112 # Configuration loaded
--> Waiting for redis socket
Starting PostgreSQL
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
Creating admin user
User created.
touch: cannot touch '/data/created_gvm_user': No such file or directory
Starting Redis
7:C 27 Oct 2020 11:56:53.449 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 11:56:53.449 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 11:56:53.449 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
7:C 27 Oct 2020 11:58:17.839 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 11:58:17.839 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 11:58:17.839 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
7:C 27 Oct 2020 11:59:33.998 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 11:59:33.998 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 11:59:33.998 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
7:C 27 Oct 2020 12:00:50.147 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 12:00:50.147 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 12:00:50.148 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
7:C 27 Oct 2020 12:02:06.453 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 12:02:06.453 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 12:02:06.453 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
7:C 27 Oct 2020 12:03:22.503 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 12:03:22.503 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 12:03:22.503 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
7:C 27 Oct 2020 12:04:38.673 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 12:04:38.673 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 12:04:38.673 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
9:C 27 Oct 2020 12:05:54.734 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
9:C 27 Oct 2020 12:05:54.734 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=9, just started
9:C 27 Oct 2020 12:05:54.734 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
7:C 27 Oct 2020 12:07:10.790 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Oct 2020 12:07:10.790 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Oct 2020 12:07:10.790 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket
Starting GVMd
--> Waiting for GVMd socket
admin
Creating admin user
User exists already.
Starting Redis
11:C 27 Oct 2020 12:08:26.984 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
11:C 27 Oct 2020 12:08:26.984 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=11, just started
11:C 27 Oct 2020 12:08:26.984 # Configuration loaded
Starting PostgreSQL
Removed stale pid file.
Starting OSPd
--> Removing stale ospd-openvas.pid file
--> Removing stale ospd.sock file
--> Waiting for OSPd socket
--> Waiting for OSPd socket
--> Waiting for OSPd socket"

Thanks,

**Comment by jeffleder** [comment]
The latest builds prevent this issue.
